name: Postman htmlextra report

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Install Newman and htmlextra
        run: npm install -g newman newman-reporter-htmlextra

      - name: Execute Trello Postman Collection
        run: |
          mkdir -p reports
          newman run "https://api.postman.com/collections/33274775-b2a05e16-355c-4564-9909-b729ad24f5c2?apikey=${{ secrets.POSTMAN_API_KEY }}" \
            -e "https://api.postman.com/environments/33274775-713aba76-28fb-47a2-a55f-ffb006a117de?apikey=${{ secrets.POSTMAN_API_KEY }}" \
            --reporters htmlextra \
            --reporter-htmlextra-export reports/report.html

      - name: Mask sensitive info in report
        run: |
          sed -i "s/${{ secrets.TRELLO_KEY }}/****/g" reports/report.html
          sed -i "s/${{ secrets.TRELLO_TOKEN }}/****/g" reports/report.html

      - name: Publish report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
